providers = ["python"]

[phases.setup]
nixPkgs = ["python312", "ffmpeg", "gcc", "musl-dev"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
